[package]
name = "orinium_text"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
unicode-bidi = "0.3"
unicode-linebreak = "0.1"

fontdb = "0.23"
fontdue = "0.9"
rustybuzz = "0.20"
sys-locale = "0.3"

[target.'cfg(target_os = "linux")'.dependencies]
fontconfig = { version = "0.11", features = ["dlopen"] }

[features]
default = ["render"]
layout-text = []
render = []
